kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: openjdk-app
  namespace: prova1
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - openjdk-app
        from:
          kind: ImageStreamTag
          namespace: prova
          name: 'openjdk-app:latest'
        lastTriggeredImage: >-
          quay-registry-quay-quay-registry.apps.prod.cloud.giustizia-amministrativa.it/openshift_prova/openjdk-app@sha256:cafc3b83e321392d212b712d2b3f087ee0c045c67740cc2c02c64ac6554ec406
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentConfig: openjdk-app
  template:
    metadata:
      name: openjdk-app
      creationTimestamp: null
      labels:
        application: openjdk-app
        deploymentConfig: openjdk-app
    spec:
      containers:
        - name: openjdk-app
          image: >-
            quay-registry-quay-quay-registry.apps.prod.cloud.giustizia-amministrativa.it/openshift_prova/openjdk-app@sha256:cafc3b83e321392d212b712d2b3f087ee0c045c67740cc2c02c64ac6554ec406
          ports:
            - name: jolokia
              containerPort: 8778
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 75
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:

