kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: openjdk-app
  namespace: prova1
spec:
  host: openjdk-app-prova.apps.prod.cloud.giustizia-amministrativa.it
  to:
    kind: Service
    name: openjdk-app
    weight: 100
  wildcardPolicy: None
status:

